version: '3'

services:

  web:
    build: .
    command: mix phx.server  
    volumes:
      - .:/usr/src/app
    ports:
      - 4000:4000
    depends_on:
      - db

  test:
    image: phx_hello_web
    command: mix test
    environment:
      MIX_ENV: test
      PORT: 4001
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
